### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-just_a_bakery#11]
Please increase test coverage to at least 50%.
The coverage expectation will increase throughout the project.

**Comment by moriarty** [comment]
I've opened similar issues for all groups.

HBRS-MAAS/project-awesomebakery#14
HBRS-MAAS/project-autobake#11
HBRS-MAAS/project-zarvis#7
HBRS-MAAS/project-pieceofcake#14
HBRS-MAAS/project-just_a_bakery#11
HBRS-MAAS/project-gabych#6

**Comment by NareshGuru77** [comment]
@moriarty  , @argenos  could you add references to some resources for java unit tests? (maybe some online blogs like the one suggested for git branching model). 
We are not familiar with java unit tests and references would be helpful.

**Comment by argenos** [comment]
@NareshGuru77 I think in this case, Google is your friend. There's lots of information out there. I'll just link to one example [here](https://manifesto.co.uk/unit-testing-best-practices-java/). If you have more concrete questions, maybe we can help
