### ISSUE TITLE
Fix bugs found by Sonar

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-just_a_bakery#14]
Fix, and keep all bugs found by sonar out of the repository.
You should setup the sonar github plugin on your pull requests to keep new bugs from getting in.

https://sonarcloud.io/project/issues?id=project-just_a_bakery&resolved=false&severities=BLOCKER&types=BUG

**Comment by NareshGuru77** [comment]
bugs fixed. Pull request setup done using github token.
