### ISSUE TITLE
Git branching model

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project-just_a_bakery#2]
Please use a [git branching model](http://nvie.com/posts/a-successful-git-branching-model/)

**Comment by moriarty** [comment]
@NareshGuru77 it's good to see you're working on #4 with  701d7eb but don't forget this issue.

**Comment by NareshGuru77** [comment]
I have tried to use the develop branch (out of master) and a SonarQube-Fixes branch (out of develop).

@argenos , @moriarty , could you please let me know whether this is what's expected or there is more to be done?

**Comment by argenos** [comment]
@NareshGuru77 you should be pushing to feature or fix branches (preferably with prefixes or some other distinction) and merging into develop. After you have tested and when the travis build passes, you merge back to master. Every new component that you develop should have its own feature branch. Read the provided link a little more carefully!

You can take a look at how we do it in the b-it-bots [here](https://mas.b-it-center.de/gitgate/mas-group/b-it-bots-wiki/wikis/development/conventions/git/git-branching-model). The slightly modified TL;DR from that: 
* master - the stable branch
* devel - the development branch, where approved merge requests are integrated.
* release-X.Y: the release branch, where preparations are made right before merging into master
* feature/name-of-feature: New functionality that will be added to your system
* fix/small-bug-description: Fixing a bug that was found in existing code.

**Comment by NareshGuru77** [comment]
@argenos ..Thank you..
