### ISSUE TITLE
What is Travis doing?

### ISSUE THREAD

**Issue by argenos** [HBRS-MAAS/project-just_a_bakery#35]
It seems that you are no longer using `gradle run` in your scripts

**Comment by NareshGuru77** [comment]
![travis](https://user-images.githubusercontent.com/26181088/33959117-c73fca1e-e046-11e7-9e56-71d3e537a9c7.png)
@argenos ..could you let me know whether your referring to the circled content in the attachment? Travis is running "gradle sonarqube" but its supposed to run "gradle run"?

**Comment by argenos** [comment]
Both! After sonarqube it should execute gradle run

**Comment by NareshGuru77** [comment]
#39 #40 ..
Now travis also does "gradle run"..
