### ISSUE TITLE
Add the email(s) you commit with to GitHub

### ISSUE THREAD

**Issue by moriarty** [HBRS-MAAS/project-just_a_bakery#8]
Please add the email(s) which is in your git configuration to GitHub.
This is to make automated assignment contribution tracking easier.

Thanks

<img width="475" alt="screen shot 2017-11-26 at 22 37 23" src="https://user-images.githubusercontent.com/55676/33244583-97208b60-d2fa-11e7-982c-5a7020499637.png">

**Comment by NareshGuru77** [comment]
I have added my email. Could you let me know whether the change is right?

**Comment by moriarty** [comment]
Yes. Thanks. Next time you can close the issue directly.
